name: Docker Image CI

on:
  workflow_run:
    workflows: [Node.js CI]
    types: [completed]
    branches: [dockerize]

jobs:
  on-success-wfcs-sdfsdfv-sfdvsdfv:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'